/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilmIdRouteImport } from './routes/film.$id'

const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmIdRoute = FilmIdRouteImport.update({
  id: '/film/$id',
  path: '/film/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/films': typeof FilmsRoute
  '/film/$id': typeof FilmIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/films': typeof FilmsRoute
  '/film/$id': typeof FilmIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/films': typeof FilmsRoute
  '/film/$id': typeof FilmIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/films' | '/film/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/films' | '/film/$id'
  id: '__root__' | '/' | '/films' | '/film/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilmsRoute: typeof FilmsRoute
  FilmIdRoute: typeof FilmIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$id': {
      id: '/film/$id'
      path: '/film/$id'
      fullPath: '/film/$id'
      preLoaderRoute: typeof FilmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilmsRoute: FilmsRoute,
  FilmIdRoute: FilmIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
